<?php
/**
 * @category    Ch
 * @package     Ch_Entity
 * @copyright   Copyright (c) 2011 Sergey Cherepanov. (http://www.cherepanov.org.ua)
 * @license     http://www.gnu.org/licenses/gpl.html GNU GENERAL PUBLIC LICENSE v3.0
 */

/** @var $this Ch_Entity_Block_View */
/** @var $entity Ch_Entity_Model_Entity */
$entity = $this->getEntity();
?>
<?php foreach ($entity->getAttributes() as $attribute):?>
    <ul>
        <?php
        if ($attribute->getIsUserDefined()):
            $value = $this->getAttributeValue($entity, $attribute);
            if ($value):?>
        <li>
            <strong><?php echo $attribute->getFrontendLabel()?>:</strong>
            <span><?php echo $value?></span>
        </li>
        <?php endif;
        endif; ?>
    </ul>
<?php endforeach;?>
<a href="<?php echo $this->getListUrl()?>"><?php echo $this->__('Back')?></a>
